version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: flask-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"

volumes:
  mysql_data:
